config/routes.rb
Rails.application.routes.draw do
  resources :surats do
	resources :dispos
  end

  resources :notifications

  get 'scanpage/scan'
  devise_for :models
  devise_for :users
	root 'surats#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dispo.rb
class Dispo < ApplicationRecord

	belongs_to :surat
	belongs_to :user

	validates :dispo, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(read_at: nil) }
end

app/models/surat.rb
class Surat < ApplicationRecord
	belongs_to :user
	has_many :dispos, dependent: :destroy
	has_many :users, through: :dispos

	mount_uploader :image, ImageUploader

	validates_processing_of :image
	validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :surats
	has_many :dispos
	has_many :notifications, foreign_key: :recipient_id
	
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dispos_controller.rb
class DisposController < ApplicationController
	before_action :authenticate_user!
	before_action :set_dispo, only: [:edit, :update, :show, :destroy]
	before_action :set_surat, only: [:create, :edit, :show, :update, :destroy]

	def create
		@dispo = @surat.dispos.create(params[:dispo].permit(:dispo, :surat_id))
		@dispo.user_id = current_user.id

		respond_to do |format|
			if @dispo.save

			#create notification
		((@surat.users.uniq + [@surat.user]) - [current_user]).each do |user|
			Notification.create(recipient: user, actor: current_user, action: "posted", notifiable: @dispo)
		end

				format.html { redirect_to surat_path(@surat) }
				format.js
		else
			format.html { redirect_to surat_path(@surat), notice: 'Disposisi not saved'}
			format.js
			end
		end
	end

	def new
		
	end

	def destroy
		@dispo = @surat.dispos.find(params[:id])
		@dispo.destroy
		redirect_to surat_path(@surat)
	end

	def edit
		@surat = Surat.find(params[:surat_id])
		@dispo = @surat.dispos.find(params[:id])
	end

	def update
		@dispo = @surat.dispos.find(params[:id])
		respond_to do |format|
			if @dispo.update(dispo_params)
				format.html { redirect_to surat_path(@surat), notice: 'Dispo Updated'}
			else
				format.html { render :edit }
				format.json { render json @dispo.errors, status: :unprocessable_entity }
			end
		end
	end

	private
	
	def set_surat
		@surat = Surat.find(params[:surat_id])
	end

	def set_dispo
		@dispo = Dispo.find(params[:id])
	end

	def dispo_params
		params.require(:dispo).permit(:dispo)
	end


end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_action :authenticate_user!

	def index
		@notifications = Notification.where(recipient: current_user).unread
	end

	def mark_as_read
		@notifications = Notification.where(recipient: current_user).unread
		@notifications.update_all(read_at: Time.zone.now)
		render json: {success: true}
	end

end

app/controllers/scanpage_controller.rb
class ScanpageController < ApplicationController
		before_action :authenticate_user!
  def scan
  end
end

app/controllers/surats_controller.rb
class SuratsController < InheritedResources::Base
	before_action :authenticate_user!

	def create
	@surat = Surat.new(surat_params)
	@surat.user_id = current_user.id

	respond_to do |format|
      if @surat.save

        format.html { redirect_to surat_path(@surat) }
        format.js # renders create.js.erb
		end
		end
	
	end

  private

    def surat_params
      params.require(:surat).permit(:jenis_surat, :tanggal_diterima, :bulan_diterima, :tahun_diterima, :tanggal_dibuat, :bulan_dibuat, :tahun_dibuat, :nomor_surat, :asal_surat, :perihal_surat, :bidang, :status, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scanpage_helper.rb
module ScanpageHelper
end

app/helpers/surats_helper.rb
module SuratsHelper
end

app/views/dispos/_dispo.html.erb
<div class="box">
  <article class="media">
    
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= dispo.user.email %></strong> <small><%= time_ago_in_words(dispo.created_at) %></small>
          <br/>
          <%= dispo.dispo %>
        </p>
      </div>
          
    </div>
  </article>
</div>

app/views/dispos/_form.html.erb
<%= simple_form_for([@surat, @surat.dispos.build], remote: true) do |f| %>
	
<div class = "field", style="width:688px;">
	<div class = "control">
		<%= f.input :dispo, input_html: { class: 'textarea', style: 'width:1105px' }, label: "Kotak Disposisi" %>
	</div>
</div>

<%= f.button :submit, 'Leave a dispo', class:'contact submit btn btn-primary btn-xl actions is-info' %>
<% end %>

app/views/dispos/create.js.erb
$("<%= escape_javascript(render(@dispo)) %>").appendTo('#surat-dispos');

app/views/dispos/edit.html.erb
<h1 class="title is-2 has-text-grey">Editing dispo</h1>

<%= simple_form_for([@surat, @dispo]) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :dispo, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<%= f.button :submit, 'Update dispo', class:'contact submit btn btn-primary btn-xl actions is-info' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Archiv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success">
      <%= notice %>
    </p>
    <% end %>
    
    <% if alert %>
      <p class="alert alert-danger">
      <%= alert %>
    </p>
    <% end %>
    
      <%= yield %>
  </body>
</html>

app/views/surats/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Home - KNIU</title>
<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="../assets/bootstrap.min.css" type="text/css">
<!-- Custom Fonts -->
<link href='https://fonts.googleapis.com/css?family=Mrs+Sheppards%7CDosis:300,400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800;' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="../assets/font-awesome.min.css" type="text/css">
<!-- Plugin CSS -->
<link rel="stylesheet" href="../assets/animate.min.css" type="text/css">
<!-- Custom CSS -->
<link rel="stylesheet" href="../assets/style.css" type="text/css">

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    .dropbtn {
    background-color: white;
    color: black;
    padding: 16px;
    font-size: 16px;
    border: none;
    }

    .dropdown {
    position: relative;
    display: inline-block;
    }

    .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
    }

    .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    }

    .dropdown-content a:hover {background-color: #ddd;}

    .dropdown:hover .dropdown-content {display: block;}

    .dropdown:hover .dropbtn {background-color: #f05f40;}
  </style>  
  
</head>
<body id="page-top">
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
<div class="container">
  
  <!-- Brand and toggle get grouped for better mobile display -->
  
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
    <a class="navbar-brand page-scroll" href="#page-top"><img src="../assets/logo.png" alt="logolayana"></a>
  
  </div>
  
  <!-- Collect the nav links, forms, and other content for toggling -->
  
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">

      <li class="navbar-item btn-group has-dropdown is-hoverable" data-behavior="notifications" data-notifications='
        <%= render template: "notifications/index", formats: [:json] %>'>
          <div class="dropdown">
            <button class="dropbtn" data-behavior="notifications" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
            </button>
            <div class="dropdown-content" data-behavior="notification-items">
              <!--<a href="#">Link 1</a>
              <a href="#">Link 2</a>
              <a href="#">Link 3</a>  -->
            </div>
          </div>
      </li>

      <li>  <%= link_to 'History', surats_path %> </li>
      <li>  <%= link_to 'Log out', destroy_user_session_path, :method => :delete %> </li>
    </ul>
  </div>
  
<!-- /.navbar-collapse -->

  </div>

    <!-- /.container -->

</nav>

  <br>

<!-- upload section -->

<section id="contact">
  <div class="container">
    <div class="row">
       <div class="col-md-8 col-md-offset-2 text-center">
          <h2 class="section-heading">NE<b>W</b> </h2>
          <hr class="primary">
    
            <h3>
              please upload the letter picture on the button below
            </h3>
    
    <br>

<%= form_for @surat, html: { multipart: true } do |f| %>
  <% if @surat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@surat.errors.count, "error") %> prohibited this letter from being saved:</h2>
 
      <ul>
      <% @surat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= f.select(:jenis_surat, options_for_select([['Surat','Surat'], ['Dokumen','Dokumen'], ['Buku','Buku'], ['Email','Email'], ['Ka','Ka']]), { include_blank: true }, class: "col-md-12") %>
  
  <br><br>
  <div>
    <%= f.text_field :tanggal_diterima , class: "col-md-4 field", placeholder: "Tanggal diterima" %>
  </div>

  <div>
    <%= f.text_field :bulan_diterima, class: "col-md-4 field", placeholder: "Bulan diterima" %>
  </div>

  <div>
    <%= f.text_field :tahun_diterima, class: "col-md-4 field", placeholder: "Tahun diterima" %>
  </div>
  <br><br>

  <div>
    <%= f.text_field :tanggal_dibuat , class: "col-md-4 field", placeholder: "Tanggal dibuat" %>
  </div>

  <div>
    <%= f.text_field :bulan_dibuat, class: "col-md-4 field", placeholder: "Bulan dibuat" %>
  </div>

  <div>
    <%= f.text_field :tahun_dibuat, class: "col-md-4 field", placeholder: "Tahun dibuat" %>
  </div>
  <br><br>

  <div>
    <%= f.text_field :nomor_surat, class: "col-md-12 field", placeholder: "Nomor surat" %>
  </div>
  <br><br>

  <div>
    <%= f.text_field :asal_surat, class: "col-md-12 field", placeholder: "Asal surat" %>
  </div>
  <br><br>

  <div>
    <%= f.text_area :perihal_surat, class: "col-md-12 field", placeholder: "Perihal surat" %>
  </div>

  <%= f.select(:bidang, options_for_select([['Pendidikan','Pendidikan'], ['Sains','Sains'], ['Kebudayaan','Kebudayaan'], ['Komunikasi','Komunikasi']]), { include_blank: true }, class: "col-md-12") %>
  
  <br><br><br>

  <div>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
    <% end %>
  </div>
  <br>
  
  <%= f.select(:status, options_for_select([['diterima','diterima'],['disposisi','disposisi'],['selesai','selesai']]), { include_blank: true }, class: "col-md-12") %>
  <div>
    <%= f.submit "Upload" , class: "contact submit btn btn-primary btn-xl actions" %>
  </div>
  <br>

<% end %>

</div>
</div>
</div>
</section>

<br>
<!-- upload section -->


<section class="bg-dark" style="bottom:0;width:100%">
<div class="container">
<div class="row">
  <div class="col-md-12 text-center">
    <p>
            <p> </p>
      &copy; Komisi Nasional Indonesia untuk Unesco
    </p>
  </div>
</div>
</div>
</section>

<!-- jQuery -->
<script src="../assets/jquery.js"></script>
<script src="../assets/bootstrap.min.js"></script>
<script src="../assets/parallax.js"></script>
<script src="../assets/contact.js"></script>
<script src="../assets/countto.js"></script>
<script src="../assets/jquery.easing.min.js"></script>
<script src="../assets/wow.min.js"></script>
<script src="../assets/common.js"></script>
</body>
</html>

app/views/surats/edit.html.erb
<%= render 'form', surat: @surat %>

app/views/surats/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Notif - KNIU</title>
<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="../assets/bootstrap.min.css" type="text/css">
<!-- Custom Fonts -->
<link href='https://fonts.googleapis.com/css?family=Mrs+Sheppards%7CDosis:300,400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800;' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="../assets/font-awesome.min.css" type="text/css">
<!-- Plugin CSS -->
<link rel="stylesheet" href="../assets/animate.min.css" type="text/css">
<!-- Custom CSS -->
<link rel="stylesheet" href="../assets/style.css" type="text/css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="page-top">
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand page-scroll" href="#page-top"><img src="../assets/logo.png" alt="logolayana"></a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">

      <li> <%= link_to 'New', new_surat_path %> </li>
      <li> <%= link_to 'Log out', destroy_user_session_path, :method => :delete %> </li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

<br>


<!-- main col -->
<section id="contact">
<div class="container">
<div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
            <h2 class="section-heading">HI<b>STORY</b> </h2>
            <hr class="primary">
            <br>
            <br>
        </div>
    </div>

    <% @surats.each do |surat| %>
      <div class="panel panel-default">
          <div class="panel-heading"><%= link_to 'Details', surat, class: "pull-right" %><h4> <%= surat.created_at %> </h4></div>
               <div class="panel-body">
                  <div class="clearfix"></div>
                        <tr>
                          <td><%= surat.perihal_surat %></td>
                        </tr>
    

      </div>
   </div>
<% end %>

</div>
</section>

<!-- Section Footer
================================================== -->
<section class="bg-dark" style="position:fixed;bottom:0;width:100%">
<div class="container">
<div class="row">
  <div class="col-md-12 text-center">
    <p>
            <p> </p>
      &copy; Komisi Nasional Indonesia untuk Unesco
    </p>
  </div>
</div>
</div>
</section>

<!-- jQuery -->
<script src="../assets/jquery.js"></script>
<script src="../assets/bootstrap.min.js"></script>
<script src="../assets/parallax.js"></script>
<script src="../assets/contact.js"></script>
<script src="../assets/countto.js"></script>
<script src="../assets/jquery.easing.min.js"></script>
<script src="../assets/wow.min.js"></script>
<script src="../assets/common.js"></script>
</body>
</html>

app/views/surats/new.html.erb
<%= render 'form', surat: @surat %>

app/views/surats/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Details - KNIU</title>
<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="../assets/bootstrap.min.css" type="text/css">
<!-- Custom Fonts -->
<link href='https://fonts.googleapis.com/css?family=Mrs+Sheppards%7CDosis:300,400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800;' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="../assets/font-awesome.min.css" type="text/css">
<!-- Plugin CSS -->
<link rel="stylesheet" href="../assets/animate.min.css" type="text/css">
<!-- Custom CSS -->
<link rel="stylesheet" href="../assets/style.css" type="text/css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="page-top">
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand page-scroll" href="#page-top"><img src="../assets/logo.png" alt="logolayana"></a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to 'New', new_surat_path %> </li>
      <li> <%= link_to 'History', surats_path %> </li>
      <li> <%= link_to 'Log out', destroy_user_session_path, :method => :delete %> </li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

<br>


<!-- main col -->
<section id="contact">
<div class="container">
  <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
            <h2 class="section-heading">DE<b>TAILS</b> </h2>
            <hr class="primary">
            <br>
            <br>
        </div>
    </div>


   <div class="panel panel-default">
     <div class="panel-heading"> <h4><%= @surat.tanggal_diterima %> <%= @surat.bulan_diterima %> <%= @surat.tahun_diterima %></h4></div>
      <div class="panel-body">
        
        <div class="panel-thumbnail"><%= image_tag @surat.image.thumb.url, class: "img-responsive" %></div>
        <br>
        <div class="clearfix"></div>
        
    </div>
    
    <div class="container">
    <h2>More Info</h2>
           
    <table class="table">
      <tbody>
      <tr>
        <td>Tanggal Diterima</td>
        <td><%= @surat.tanggal_diterima %></td>
      </tr>
      <tr>
        <td>Bulan Diterima</td>
        <td><%= @surat.bulan_diterima %></td>
      </tr>
      <tr>
        <td>Tahun Diterima</td>
        <td><%= @surat.tahun_diterima %></td>
      </tr>
      <tr>
        <td>Tanggal Dibuat</td>
        <td><%= @surat.tanggal_dibuat %></td>
      </tr>
      <tr>
        <td>Bulan Dibuat</td>
        <td><%= @surat.bulan_dibuat %></td>
      </tr>
      <tr>
        <td>Tahun Dibuat</td>
        <td><%= @surat.tahun_dibuat %></td>
      </tr>
      <tr>
        <td>Jenis Surat</td>
        <td><%= @surat.jenis_surat %></td>
      </tr>
      <tr>
        <td>Nomor surat</td>
        <td><%= @surat.nomor_surat %></td>
      </tr>
      <tr>
        <td>Asal Surat</td>
        <td><%= @surat.asal_surat %></td>
      </tr>
      <tr>
        <td>Perihal Surat</td>
        <td><%= @surat.perihal_surat %></td>
      </tr>
      <tr>
        <td>Bidang</td>
        <td><%= @surat.bidang %></td>
      </tr>
      </tbody>
    </table>
    </div>
    <div class="container">
    <h3>Status Surat</h3>
    </div>  
    <% if(@surat.status == "diterima") %>          
    <div class="container">
      
    <div class="row bs-wizard" style="border-bottom:0;">
        
        <div class="col-xs-3 bs-wizard-step active">
          <div class="text-center bs-wizard-stepnum">Step 1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Diterima</div>
          <endif>
        </div>
        
        <div class="col-xs-3 bs-wizard-step disabled"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">Step 2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Disposisi</div>
          <endif>
        </div>
        
        <div class="col-xs-3 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">Step 3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Selesai</div>
        </div>
    </div>
    <% elsif(@surat.status == "disposisi") %> 
    <div class="container">
  
      
    <div class="row bs-wizard" style="border-bottom:0;">
        
        <div class="col-xs-3 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">Step 1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          
          <div class="bs-wizard-info text-center">Diterima</div>
          <endif>
        </div>
        
        <div class="col-xs-3 bs-wizard-step active"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">Step 2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a> 
          <div class="bs-wizard-info text-center">Disposisi</div>
          <endif>
        </div>
        
        <div class="col-xs-3 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">Step 3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Selesai</div>
        </div>
    </div>
    <% elsif(@surat.status == "selesai") %>
    <div class="container">
        
    <div class="row bs-wizard" style="border-bottom:0;">
        
        <div class="col-xs-3 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">Step 1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>          
          <div class="bs-wizard-info text-center">Diterima</div>
          <endif>
        </div>
        
        <div class="col-xs-3 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">Step 2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Disposisi</div>
          <endif>
        </div>
                
        <div class="col-xs-3 bs-wizard-step complete"><!-- active -->
          <div class="text-center bs-wizard-stepnum">Step 3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Selesai</div>
        </div>
    </div>
    <% end %>

    <div class="container">
    <div id="surat-dispos">
      <h3>Disposisi :</h3>
      
      <br>
      
      <%= render @surat.dispos %></div>

      <div>
      
      <% if user_signed_in ="first@admin.com" %>
         <%= render 'dispos/form' %>
      <% else %>
      <p>
        To make a dispo you need to login as <%= link_to 'pimpinan', new_user_session_path %>. 
      </p>
      <% end %>  
      </div>
      <br>
        <%= link_to 'Edit', edit_surat_path(@surat), class: "contact submit btn btn-primary btn-xl" %>
        <%= link_to 'List', surats_path, class: "contact submit btn btn-primary btn-xl" %>
      
      <br>
      <br>
        
    </div>

   </div>


   
</div>
</section>


<!-- Section Footer
================================================== -->
<section class="bg-dark" style="width:100%;">
<div class="container">
<div class="row">
  <div class="col-md-12 text-center">
    <p>
            <p> </p>
      &copy; Komisi Nasional Indonesia untuk Unesco
    </p>
  </div>
</div>
</div>
</section>

<!-- jQuery -->
<script src="../assets/jquery.js"></script>
<script src="../assets/bootstrap.min.js"></script>
<script src="../assets/parallax.js"></script>
<script src="../assets/contact.js"></script>
<script src="../assets/countto.js"></script>
<script src="../assets/jquery.easing.min.js"></script>
<script src="../assets/wow.min.js"></script>
<script src="../assets/common.js"></script>
</body>
</html>